"""add_2fa_fields

Revision ID: bc471d4214d7
Revises: 951003fb6089
Create Date: 2026-06-04 05:57:18.809019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc471d4214d7'
down_revision: Union[str, None] = '951003fb6089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
